version: "3.8"
services:
  manager:
    build: .
    environment: 
      - POSTGRES_PASSWORD=motdepasse
      - POSTGRES_USER=username
      - POSTGRES_DB=mydatabase
      - CSV_FILENAME=data.csv
  db:
    image: "postgres:latest"
    environment: 
      - POSTGRES_PASSWORD=motdepasse
      - POSTGRES_USER=username
      - POSTGRES_DB=mydatabase
    
    